"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-change-me-for-local-development')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'true').lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver']

# Comma-separated origins, including the scheme and port. Trust the local Vite
# development server by default while keeping CSRF validation enabled.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'DJANGO_CSRF_TRUSTED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173',
    ).split(',')
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pipecloud',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'pipecloud.middleware.OperationLogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

MYSQL_DATABASE = os.getenv('MYSQL_DATABASE', 'pipecloud')
MYSQL_USER = os.getenv('MYSQL_USER', 'root')
MYSQL_PASSWORD = os.getenv('MYSQL_PASSWORD', '123456')
MYSQL_HOST = os.getenv('MYSQL_HOST', '127.0.0.1')
MYSQL_PORT = os.getenv('MYSQL_PORT', '3306')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': MYSQL_DATABASE,
        'USER': MYSQL_USER,
        'PASSWORD': MYSQL_PASSWORD,
        'HOST': MYSQL_HOST,
        'PORT': MYSQL_PORT,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

PLAN_ROLLOVER_HOUR = int(os.getenv('PIPECLOUD_PLAN_ROLLOVER_HOUR', '21'))
PLAN_ROLLOVER_MINUTE = int(os.getenv('PIPECLOUD_PLAN_ROLLOVER_MINUTE', '0'))
PLAN_ROLLOVER_MISFIRE_GRACE_SECONDS = int(
    os.getenv('PIPECLOUD_PLAN_ROLLOVER_MISFIRE_GRACE_SECONDS', '3600')
)

SCHEDULED_MAINTENANCE_JOBS = [
    {
        'key': 'sync-anti-corrosion-completion',
        'kind': 'completion-sync',
        'command': 'sync_anti_corrosion_completion',
        'name': '同步防腐计划中防腐完成情况',
        'hour': int(os.getenv('PIPECLOUD_ANTI_CORROSION_COMPLETION_SYNC_HOUR', '21')),
        'minute': int(os.getenv('PIPECLOUD_ANTI_CORROSION_COMPLETION_SYNC_MINUTE', '0')),
        'enabled': os.getenv('PIPECLOUD_ANTI_CORROSION_COMPLETION_SYNC_ENABLED', 'true').lower() != 'false',
    },
    {
        'key': 'sync-cutting-completion',
        'kind': 'completion-sync',
        'command': 'sync_cutting_completion',
        'name': '同步下料计划中下料完成情况',
        'hour': int(os.getenv('PIPECLOUD_CUTTING_COMPLETION_SYNC_HOUR', '21')),
        'minute': int(os.getenv('PIPECLOUD_CUTTING_COMPLETION_SYNC_MINUTE', '5')),
        'enabled': os.getenv('PIPECLOUD_CUTTING_COMPLETION_SYNC_ENABLED', 'true').lower() != 'false',
    },
    {
        'key': 'sync-welding-completion',
        'kind': 'completion-sync',
        'command': 'sync_welding_completion',
        'name': '同步焊接计划中焊接完成情况',
        'hour': int(os.getenv('PIPECLOUD_WELDING_COMPLETION_SYNC_HOUR', '21')),
        'minute': int(os.getenv('PIPECLOUD_WELDING_COMPLETION_SYNC_MINUTE', '10')),
        'enabled': os.getenv('PIPECLOUD_WELDING_COMPLETION_SYNC_ENABLED', 'true').lower() != 'false',
    },
    {
        'key': 'rollover-cutting-plan',
        'kind': 'plan-rollover',
        'command': 'rollover_cutting_plan',
        'name': '滚动未完成下料计划',
        'hour': int(os.getenv('PIPECLOUD_CUTTING_PLAN_ROLLOVER_HOUR', '21')),
        'minute': int(os.getenv('PIPECLOUD_CUTTING_PLAN_ROLLOVER_MINUTE', '20')),
        'enabled': os.getenv('PIPECLOUD_CUTTING_PLAN_ROLLOVER_ENABLED', 'true').lower() != 'false',
    },
    {
        'key': 'rollover-welding-plan',
        'kind': 'plan-rollover',
        'command': 'rollover_welding_plan',
        'name': '滚动未完成焊接计划',
        'hour': int(os.getenv('PIPECLOUD_WELDING_PLAN_ROLLOVER_HOUR', '21')),
        'minute': int(os.getenv('PIPECLOUD_WELDING_PLAN_ROLLOVER_MINUTE', '30')),
        'enabled': os.getenv('PIPECLOUD_WELDING_PLAN_ROLLOVER_ENABLED', 'true').lower() != 'false',
    },
]
PLAN_COMPLETION_SYNC_MISFIRE_GRACE_SECONDS = int(
    os.getenv('PIPECLOUD_PLAN_COMPLETION_SYNC_MISFIRE_GRACE_SECONDS', str(PLAN_ROLLOVER_MISFIRE_GRACE_SECONDS))
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
