# Generated by Django 6.0.5 on 2026-06-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipecloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdetailrow',
            name='design_qty',
            field=models.CharField(blank=True, max_length=80, verbose_name='设计数量'),
        ),
        migrations.AddField(
            model_name='materialdetailrow',
            name='pick_qty',
            field=models.CharField(blank=True, max_length=80, verbose_name='需领料数量'),
        ),
        migrations.CreateModel(
            name='FittingPickListRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(blank=True, max_length=120, verbose_name='工作表')),
                ('row_index', models.IntegerField(default=0, verbose_name='行号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('material_code', models.CharField(blank=True, max_length=120, verbose_name='材料代码')),
                ('material_paint', models.CharField(blank=True, max_length=120, verbose_name='材料油漆')),
                ('material_mark', models.CharField(blank=True, max_length=120, verbose_name='材料代号')),
                ('unit_name', models.CharField(blank=True, max_length=40, verbose_name='单位')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('design_qty', models.CharField(blank=True, max_length=80, verbose_name='设计数量')),
                ('pick_qty', models.CharField(blank=True, max_length=80, verbose_name='需领料数量')),
                ('pipeline', models.CharField(blank=True, max_length=255, verbose_name='管线号')),
                ('segment_no', models.CharField(blank=True, max_length=120, verbose_name='管段号')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipecloud.project', verbose_name='项目')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipecloud.datasourcefile', verbose_name='来源文件')),
            ],
            options={
                'verbose_name': '管件法兰领料单',
                'verbose_name_plural': '管件法兰领料单',
                'ordering': ['project', 'source_file', 'sheet_name', 'row_index'],
            },
        ),
        migrations.CreateModel(
            name='PipePickListRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(blank=True, max_length=120, verbose_name='工作表')),
                ('row_index', models.IntegerField(default=0, verbose_name='行号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('material_code', models.CharField(blank=True, max_length=120, verbose_name='材料代码')),
                ('material_paint', models.CharField(blank=True, max_length=120, verbose_name='材料油漆')),
                ('material_mark', models.CharField(blank=True, max_length=120, verbose_name='材料代号')),
                ('unit_name', models.CharField(blank=True, max_length=40, verbose_name='单位')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('design_qty', models.CharField(blank=True, max_length=80, verbose_name='设计数量')),
                ('pick_qty', models.CharField(blank=True, max_length=80, verbose_name='需领料数量')),
                ('pipeline', models.CharField(blank=True, max_length=255, verbose_name='管线号')),
                ('segment_no', models.CharField(blank=True, max_length=120, verbose_name='管段号')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipecloud.project', verbose_name='项目')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipecloud.datasourcefile', verbose_name='来源文件')),
            ],
            options={
                'verbose_name': '管子领料单',
                'verbose_name_plural': '管子领料单',
                'ordering': ['project', 'source_file', 'sheet_name', 'row_index'],
            },
        ),
    ]
