# Generated by Django 6.0.5 on 2026-06-23 08:17

from django.db import migrations, models


TRUE_VALUES = {'1', 'true', 't', 'yes', 'y', '是', '已完成', '完成'}


def normalize_weld_library_completed_flag(apps, schema_editor):
    WeldLibraryRow = apps.get_model('pipecloud', 'WeldLibraryRow')
    updates = []
    for row in WeldLibraryRow.objects.using(schema_editor.connection.alias).only('id', 'completed_flag').iterator():
        value = row.completed_flag
        if isinstance(value, bool):
            normalized = '1' if value else '0'
        elif value is None:
            normalized = '0'
        else:
            normalized = '1' if str(value).strip().lower() in TRUE_VALUES else '0'
        if row.completed_flag != normalized:
            row.completed_flag = normalized
            updates.append(row)
    if updates:
        WeldLibraryRow.objects.using(schema_editor.connection.alias).bulk_update(updates, ['completed_flag'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('pipecloud', '0002_materialdetailrow_design_qty_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_weld_library_completed_flag, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='weldlibraryrow',
            name='completed_flag',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
    ]
