# Generated by Codex on 2026-06-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipecloud', '0005_welding_plan_split_material_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=64, unique=True, verbose_name='任务ID')),
                ('file_type', models.CharField(max_length=16, verbose_name='文件类型')),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '解析中'), ('completed', '已完成'), ('failed', '失败')], default='queued', max_length=24, verbose_name='状态')),
                ('total', models.IntegerField(default=0, verbose_name='子任务总数')),
                ('completed', models.IntegerField(default=0, verbose_name='完成子任务数')),
                ('failed', models.IntegerField(default=0, verbose_name='失败子任务数')),
                ('percent', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('current', models.CharField(blank=True, max_length=255, verbose_name='当前进度')),
                ('message', models.TextField(blank=True, verbose_name='消息')),
                ('batch_path', models.CharField(blank=True, max_length=500, verbose_name='任务目录')),
                ('input_hash', models.CharField(db_index=True, max_length=64, verbose_name='输入哈希')),
                ('input_files', models.JSONField(blank=True, default=list, verbose_name='输入文件')),
                ('results', models.JSONField(blank=True, default=list, verbose_name='解析结果')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parser_jobs', to='pipecloud.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '解析任务',
                'verbose_name_plural': '解析任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParserSubtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='子任务序号')),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '解析中'), ('completed', '已完成'), ('failed', '失败')], default='queued', max_length=24, verbose_name='状态')),
                ('input_files', models.JSONField(blank=True, default=list, verbose_name='输入文件')),
                ('file_count', models.IntegerField(default=0, verbose_name='文件数量')),
                ('work_path', models.CharField(blank=True, max_length=500, verbose_name='工作目录')),
                ('result_path', models.CharField(blank=True, max_length=500, verbose_name='结果路径')),
                ('result_payload', models.JSONField(blank=True, default=dict, verbose_name='结果载荷')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='pipecloud.parserjob', verbose_name='解析任务')),
            ],
            options={
                'verbose_name': '解析子任务',
                'verbose_name_plural': '解析子任务',
                'ordering': ['job', 'index'],
            },
        ),
        migrations.AddConstraint(
            model_name='parserjob',
            constraint=models.UniqueConstraint(fields=('project', 'file_type', 'input_hash'), name='pipecloud_parser_job_unique_input'),
        ),
        migrations.AddConstraint(
            model_name='parsersubtask',
            constraint=models.UniqueConstraint(fields=('job', 'index'), name='pipecloud_parser_subtask_unique_index'),
        ),
    ]
